# **what?**
# The purpose of this workflow is to trigger CI to run for each
# release branch and main branch on a regular cadence. If the CI workflow
# fails for a branch, it will post to dev-core-alerts to raise awareness.

# **why?**
# Ensures release branches and main are always shippable and not broken.
# Also, can catch any dependencies shifting beneath us that might
# introduce breaking changes (could also impact Cloud).

# **when?**
# Mainly on a schedule of 9:00, 13:00, 18:00 UTC everyday.
# Manual trigger can also test on demand

name: Release branch scheduled testing

on:
  schedule:
    - cron: '0 9,13,18 * * *' # 9:00, 13:00, 18:00 UTC

  workflow_dispatch: # for manual triggering

# no special access is needed
permissions: read-all

jobs:
  run_tests:
    uses: dbt-labs/actions/.github/workflows/release-branch-tests.yml@main
    with:
      workflows_to_run: '["main.yml", "integration.yml"]'
      include_main: false
    secrets: inherit
